routes/auth.py
from flask import Blueprint, request, jsonify, session
from db.queries import create_node, list_nodes
from utils.helpers import hash_password, verify_password

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/api/login', methods=['POST'])
def api_login():
    username = request.json.get('username')
    password = request.json.get('password')
    if not username or not password:
        return jsonify({'message': 'Username and password are required'}), 400
    
    user = list_nodes({'labels': ['User'], 'username': username})
    if not user:
        return jsonify({'message': 'User not found'}), 404
    
    hashed_password = user[0]['password']
    if not verify_password(hashed_password, password):
        return jsonify({'message': 'Incorrect password'}), 401

    session['logged_in'] = True
    session['id'] = user[0]['id']
    session['username'] = user[0]['username']
    return jsonify({'message': 'Login successful'}), 200


@auth_bp.route('/api/signup', methods=['POST'])
def api_signup():
    username = request.json.get('username')
    password = request.json.get('password')
    if not username or not password:
        return jsonify({'message': 'Username and password are required'}), 400
    
    if list_nodes({'labels': ['User'], 'username': username}):
        return jsonify({'message': 'Username already exists'}), 409
    
    hashed_password = hash_password(password)
    user = create_node({'username': username, 'password': hashed_password, 'labels': ['User'], 'title': username, 'slug': 'usr'})
    session['logged_in'] = True
    session['id'] = user['id']
    session['username'] = username
    return jsonify({'message': 'Signup successful'}), 201


@auth_bp.route('/api/logout', methods=['POST'])
def api_logout():
    if not 'logged_in' in session or not session['logged_in']:
        return jsonify({'message': 'You are not logged in'}), 401
    session.clear()
    return jsonify({'message': 'Logout successful'}), 200

routes/files.py
from flask import Blueprint, request, jsonify, session, send_from_directory
from werkzeug.utils import secure_filename
import os
import uuid

files_bp = Blueprint('files', __name__)

FILE_DIR = 'static/files'
if not os.path.exists(FILE_DIR):
    os.makedirs(FILE_DIR)

@files_bp.route('/api/files/<file_id>', methods=['GET'])
def api_get_file(file_id):
    file_path = os.path.join(FILE_DIR, file_id)
    if not os.path.exists(file_path):
        return jsonify({'message': 'File not found'}), 404
    return send_from_directory(FILE_DIR, file_id, as_attachment=True)

@files_bp.route('/api/files', methods=['POST'])
def api_create_file():
    if not 'logged_in' in session or not session['logged_in']:
        return jsonify({'message': 'You do not have permission to upload files'}), 403
    
    file = request.files.get('file')
    if not file:
        return jsonify({'message': 'File is required'}), 400
    
    original_filename = secure_filename(file.filename)
    filename_base, file_extension = os.path.splitext(original_filename)

    random_uuid = uuid.uuid4().hex
    new_filename = f"{filename_base}_{random_uuid}{file_extension}"
    
    file_path = os.path.join(FILE_DIR, new_filename)
    file.save(file_path)
    
    return jsonify({'id': new_filename}), 201

@files_bp.route('/api/files/<file_id>', methods=['DELETE'])
def api_delete_file(file_id):
    if not 'logged_in' in session or not session['logged_in']:
        return jsonify({'message': 'You do not have permission to delete files'}), 403
    
    file_path = os.path.join(FILE_DIR, file_id)
    if not os.path.exists(file_path):
        return jsonify({'message': 'File not found'}), 404
    
    os.remove(file_path)
    return jsonify({'message': 'File deleted successfully'}), 200

routes/graph.py
from flask import Blueprint, request, jsonify
from db.queries import get_node, list_nodes, create_node, create_node_batch, list_node_labels, update_node, delete_node, create_index, get_edge, create_edge, create_edge_batch, list_edges
from config import Config
import json

graph_bp = Blueprint('graph', __name__)

@graph_bp.route('/api/nodes/<id>', methods=['GET'])
def api_get_node(id):
    node = get_node(id)
    if node is None:
        return jsonify({'message': 'Node not found'}), 404
    for field in Config.HIDDEN_FIELDS:
        if field in node:
            del node[field]
    return node


@graph_bp.route('/api/nodes', methods=['GET'])
def api_list_nodes():
    page = int(request.args.get('page', 1))
    page_size = int(request.args.get('page_size', 10))
    start_date = request.args.get('start_date')
    end_date = request.args.get('end_date')
    sort_by = request.args.get('sort_by')
    sort_order = request.args.get('sort_order')
    query = request.args.get('q', "")
    filters = {}
    if 'filter' in request.args:
        filters = json.loads(request.args['filter'])
    
    nodes = list_nodes(filters=filters, query=query, page=page, page_size=page_size, start_date=start_date, end_date=end_date, sort_by=sort_by, sort_order=sort_order)
    for node in nodes:
        for field in Config.HIDDEN_FIELDS:
            if field in node:
                del node[field]
    return jsonify({"results": nodes})


@graph_bp.route('/api/nodes', methods=['POST'])
def api_create_node():
    properties = request.json
    
    if 'labels' not in properties:
        return jsonify({'message': 'Label array is required'}), 400
    
    reserved_fields_used = set(properties.keys()).intersection(Config.RESERVED_FIELDS)
    if reserved_fields_used:
        return jsonify({'message': f'Reserved fields used: {reserved_fields_used}'}), 400

    reserved_labels_used = set(properties['labels']).intersection(Config.RESERVED_LABELS)
    if reserved_labels_used:
        return jsonify({'message': f'Reserved labels used: {reserved_labels_used}'}), 400
    
    node = create_node(properties)
    if node is None:
        return jsonify({'message': 'Node not created'}), 500
    return jsonify(node), 201


@graph_bp.route('/api/nodes/<node_id>', methods=['PUT'])
def api_update_node(node_id):
    properties = request.json
    labels = properties.get('labels', [])
    
    reserved_fields_used = set(properties.keys()).intersection(Config.RESERVED_FIELDS)
    if reserved_fields_used:
        return jsonify({'message': f'Reserved fields used: {reserved_fields_used}'}), 400
    
    reserved_labels_used = set(labels).intersection(Config.RESERVED_LABELS)
    if reserved_labels_used:
        return jsonify({'message': f'Reserved labels used: {reserved_labels_used}'}), 400
    
    node = update_node(node_id, properties)
    if node is None:
        return jsonify({'message': 'Node not found'}), 404
    return jsonify(node), 200


@graph_bp.route('/api/nodes/<node_id>', methods=['DELETE'])
def api_delete_node(node_id):
    node = delete_node(node_id)
    if node is None:
        return jsonify({'message': 'Node not found'}), 404
    return jsonify({'message': 'Node deleted successfully'}), 200


@graph_bp.route('/api/nodes/batch', methods=['POST'])
def api_create_node_batch():
    nodes = request.json
    
    if not isinstance(nodes, list):
        return jsonify({'message': 'A list of node data is required'}), 400
    
    for properties in nodes:
        if 'labels' not in properties:
            return jsonify({'message': 'Label array is required'}), 400
        
        reserved_fields_used = set(properties.keys()).intersection(Config.RESERVED_FIELDS)
        if reserved_fields_used:
            return jsonify({'message': f'Reserved fields used: {reserved_fields_used}'}), 400

        reserved_labels_used = set(properties['labels']).intersection(Config.RESERVED_LABELS)
        if reserved_labels_used:
            return jsonify({'message': f'Reserved labels used: {reserved_labels_used}'}), 400
    
    result = create_node_batch(nodes)
    if result is None:
        return jsonify({'message': 'Nodes not created'}), 500
    return jsonify(result), 201


@graph_bp.route('/api/edges/<id>', methods=['GET'])
def api_get_edge(id):
    edge = get_edge(id)
    if edge is None:
        return jsonify({'message': 'Edge not found'}), 404
    for field in Config.HIDDEN_FIELDS:
        if field in edge:
            del edge[field]
    return edge


@graph_bp.route('/api/edges', methods=['GET'])
def api_list_edges():
    page = int(request.args.get('page', 1))
    page_size = int(request.args.get('page_size', 10))
    start_date = request.args.get('start_date')
    end_date = request.args.get('end_date')
    sort_by = request.args.get('sort_by')
    sort_order = request.args.get('sort_order')
    filters = {}
    if 'filter' in request.args:
        filters = json.loads(request.args['filter'])
    
    edges = list_edges(filters=filters, page=page, page_size=page_size, start_date=start_date, end_date=end_date, sort_by=sort_by, sort_order=sort_order)
    for edge in edges:
        for field in Config.HIDDEN_FIELDS:
            if field in edge:
                del edge[field]
    return jsonify({"results": edges})


@graph_bp.route('/api/edges', methods=['POST'])
def api_create_edge():
    data = request.json
    if 'src' not in data or 'dst' not in data:
        return jsonify({'message': 'Source and destination are required'}), 400
    reserved_fields_used = set(data.keys()).intersection(Config.RESERVED_FIELDS)
    if reserved_fields_used:
        return jsonify({'message': f'Reserved fields used: {reserved_fields_used}'}), 400
    edge = create_edge(data)
    if edge is None:
        return jsonify({'message': 'Edge not created'}), 500
    return jsonify(edge), 201


@graph_bp.route('/api/edges/batch', methods=['POST'])
def api_create_edge_batch():
    edges = request.json
    if not isinstance(edges, list):
        return jsonify({'message': 'A list of edge data is required'}), 400
    for data in edges:
        if 'src' not in data or 'dst' not in data:
            return jsonify({'message': 'Source and destination are required'}), 400
        reserved_fields_used = set(data.keys()).intersection(Config.RESERVED_FIELDS)
        if reserved_fields_used:
            return jsonify({'message': f'Reserved fields used: {reserved_fields_used}'}), 400
    result = create_edge_batch(edges)
    if result is None:
        return jsonify({'message': 'Edges not created'}), 500
    return jsonify(result), 201


@graph_bp.route('/api/labels', methods=['GET'])
def api_list_node_labels():
    labels = list_node_labels()
    return jsonify({"labels": labels})

routes/main.py
from flask import Blueprint, render_template, redirect, url_for, request, session, jsonify
from db.queries import list_nodes, get_node, list_node_labels, get_graph_neighborhood
from utils.helpers import create_openai_completion, create_openai_transcription
import json
from config import Config

main_bp = Blueprint('main', __name__)


@main_bp.route('/', methods=['GET'])
def index():
    recent_items = list_nodes()
    labels = list_node_labels()
    data = {
        'graph': get_graph_neighborhood([item['id'] for item in recent_items]),
        'labels': labels,
    }
    return render_template('index.html', data=data)


@main_bp.route('/search', methods=['GET'])
def search():
    page = int(request.args.get('page', 1))
    page_size = int(request.args.get('page_size', 10))
    query = request.args.get('q', '')
    start_date = request.args.get('start_date')
    end_date = request.args.get('end_date')
    insights = request.args.get('insights') == 'true'
    filters = request.args.get('filter', '{}')
    filters = json.loads(filters)
    
    labels = list_node_labels()
    nodes = list_nodes(filters=filters, query=query, page=page, page_size=page_size, start_date=start_date, end_date=end_date)
    for node in nodes:
        for field in Config.HIDDEN_FIELDS:
            if field in node:
                del node[field]
    
    data = {
        'results': nodes,
        'graph': get_graph_neighborhood([node['id'] for node in nodes]),
        'labels': labels,
    }
    return render_template('search.html', data=data, insights=insights)


@main_bp.route('/items/<item_id>', methods=['GET'])
def get_item(item_id):
    node = get_node(item_id)
    for field in Config.HIDDEN_FIELDS:
            if field in node:
                del node[field]
    if node is None:
        return redirect(url_for('main.index'))
    data = {
        'item': node,
        'labels': list_node_labels(),
        'graph': get_graph_neighborhood([item_id])
    }
    return render_template('get_item.html', data=data)


@main_bp.route('/new', methods=['GET'])
def create_item():
    if not 'logged_in' in session or not session['logged_in']:
        return redirect(url_for('main.index'))
    labels = list_node_labels()
    return render_template('create_item.html', data={"labels": labels})



@main_bp.route('/api/chat/completions', methods=['POST'])
def api_create_completion():
    messages = request.json.get('messages')
    return create_openai_completion(messages)


@main_bp.route('/api/audio/transcriptions', methods=['POST'])
def api_create_transcription():
    file = request.files.get('file')
    if not file:
        return jsonify({'message': 'File is required'}), 400
    allowed_formats = ['flac', 'm4a', 'mp3', 'mp4', 'mpeg', 'mpga', 'oga', 'ogg', 'wav', 'webm']
    file_extension = file.filename.split('.')[-1].lower()
    if file_extension not in allowed_formats:
        return jsonify({'message': f"Unsupported file format. Supported formats: {allowed_formats}, got '{file_extension}'"}), 400
    text = create_openai_transcription(file)
    return jsonify({'text': text})

templates/base.html
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Graph Knowledge Base</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.8/dist/trix.css">
    <script type="text/javascript" src="https://unpkg.com/trix@2.0.8/dist/trix.umd.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.30.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/4.2.2/masonry.pkgd.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/5.0.0/imagesloaded.pkgd.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/7.9.0/d3.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/12.0.2/marked.min.js"></script>
    <script>
        const url_signup = {{ url_for("auth.api_signup")|tojson }}
        const url_login = {{ url_for("auth.api_login")|tojson }}
        const url_logout = {{ url_for("auth.api_logout")|tojson }}
        const url_list_items = {{ url_for("graph.api_list_nodes")|tojson }}
        const url_create_item = {{ url_for("graph.api_create_node")|tojson }}
        const url_update_item = {{ url_for("graph.api_update_node", node_id="NODE_ID")|tojson }}
        const url_delete_item = {{ url_for("graph.api_delete_node", node_id="NODE_ID")|tojson }}
        const url_create_completion = {{ url_for("main.api_create_completion")|tojson }}
        const url_get_file = {{ url_for("files.api_get_file", file_id="FILE_ID")|tojson }}
        const url_create_file = {{ url_for("files.api_create_file")|tojson }}
        const url_delete_file = {{ url_for("files.api_delete_file", file_id="FILE_ID")|tojson }}
        const url_create_transcription = {{ url_for("main.api_create_transcription")|tojson }}
        const url_list_nodes = {{ url_for("graph.api_list_nodes")|tojson }}

        function setElementVisibility(elements) {
            for (const [key, visible] of Object.entries(elements)) {
                const element = document.querySelector(key);
                if (element) {
                    if (visible) {
                        element.classList.remove('d-none');
                    } else {
                        element.classList.add('d-none');
                    }
                }
            }
        }

        function htmlToPlain(html){
            tempDivElement = document.createElement("div");
            tempDivElement.innerHTML = html;
            return tempDivElement.textContent || tempDivElement.innerText || "";
        }

    </script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="{{ url_for('static',filename='styles/styles.css') }}">

    <link rel="icon" type="image/x-icon" href="{{ url_for('static',filename='icons/graph.png') }}">
</head>
<body class="d-flex flex-column h-100">
    <nav class="navbar navbar-expand-md">
        <div class="container-fluid">
        <a class="navbar-brand" href="/"><img src="{{ url_for('static',filename='icons/graph.png') }}" id="logo">Knowledge Graph</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end gap-3" id="navbarSupportedContent">
            
            <ul class="navbar-nav mb-2 mb-lg-0">
                {% if 'logged_in' in session and session['logged_in'] %}
                
                <a href="/new" class="btn btn-primary me-3" id="btn-go-create-item"><i class="bi bi-plus-lg"></i> Create </a>

                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {{ session['username'] }}
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li><a class="dropdown-item" href="javascript:void(0)" id="btn-logout" onclick="logOut()">Log out</a></li>
                </ul>
                </li>
                {% else %}
                <li class="nav-item">
                <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#modal-login">Log in</a>
                </li>
                <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal-signup">Sign up</button>
                {% endif %}
            </ul>
            </div>
        </div>
    </nav>
    <div class="modal fade" id="modal-signup" tabindex="-1" aria-labelledby="modal-signup-label" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-signup-label">Sign up</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form-signup" onsubmit="return validateSignupForm();">
                    <div class="mb-3">
                        <label for="input-signup-username" class="form-label">Username</label>
                        <input type="text" class="form-control" id="input-signup-username" name="username" autocomplete="username" required>
                    </div>
                    <div class="mb-3">
                        <label for="input-signup-password" class="form-label">Password</label>
                        <input type="password" class="form-control" id="input-signup-password" name="password" required>
                    </div>
                    <div class="alert alert-warning collapse" id="message-signup-error">
                        Error
                    </div>
                    <button type="submit" class="btn btn-primary w-100 mb-3" id="btn-signup">Sign up</button>
                    <p>Already have an account? <a id="link-login-modal" href="javascript:void(0)">Log in</a></p>
                </form>
            </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal-login" tabindex="-1" aria-labelledby="modal-login-label" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-login-label">Log in</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form-login" onsubmit="return validateLoginForm();">
                    <div class="mb-3">
                        <label for="input-login-username" class="form-label">Username</label>
                        <input type="text" class="form-control" id="input-login-username" name="username" autocomplete="username" required>
                    </div>
                    <div class="mb-3">
                        <label for="input-login-password" class="form-label">Password</label>
                        <input type="password" class="form-control" id="input-login-password" name="password" required>
                    </div>
                    <div class="alert alert-warning collapse" id="message-login-error">
                        Error
                    </div>
                    <div class="alert alert-success collapse" id="message-login-success">
                        Success
                    </div>
                    <button type="submit" class="btn btn-primary w-100 mb-3" id="btn-login">Log in</button>
                    <p>Don't have an account? <a id="link-signup-modal" href="javascript:void(0)">Sign up</a></p>
                </form>
            </div>
            </div>
        </div>
    </div>
    <main class="container-fluid" id="home-content">

        {% block content %}
        {% endblock %}
        
    </main>

    <!-- <footer class="mt-auto">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container justify-content-center">
                <a class="navbar-brand" href="https://nakhod.me">
                    Oleksii Nakhod
                </a>
                <a href="https://github.com/oleksii-nakhod/news" target="_blank">
                    <i class="fab fa-github fa-xl" style="color: white"></i>
                </a>
            </div>
        </nav>
    </footer> -->

    <script src="{{ url_for('static',filename='scripts/base.js') }}"></script>
</body>
</html>

templates/create_item.html
{% extends 'base.html' %}
{% block content %}

<h2>Create Item</h2>

{% include 'trix.html' %}

<script src="{{ url_for('static',filename='scripts/create_item.js') }}"></script>

{% endblock %}

templates/date_badges.html
<span class="date-badges">
    <a id="badge-last-day"><span class="badge rounded-pill text-bg-success">Last 24 hours</span></a>
    <a id="badge-last-week"><span class="badge rounded-pill text-bg-success">Last 7 days</span></a>
</span>

<script>
    function formatDate(date) {
        const year = date.getFullYear();
        const month = (date.getMonth() + 1).toString().padStart(2, '0');
        const day = date.getDate().toString().padStart(2, '0');
        return `${year}-${month}-${day}`;
    }

    function updateHrefs() {
        const today = new Date();
        const oneDayAgo = new Date(today);
        oneDayAgo.setDate(today.getDate() - 1);
        const oneWeekAgo = new Date(today);
        oneWeekAgo.setDate(today.getDate() - 7);

        const oneDayAgoStr = formatDate(oneDayAgo);
        const oneWeekAgoStr = formatDate(oneWeekAgo);

        document.getElementById('badge-last-day').href = `{{ url_for("main.search") }}?start_date=${oneDayAgoStr}`;
        document.getElementById('badge-last-week').href = `{{ url_for("main.search") }}?start_date=${oneWeekAgoStr}`;
    }

    updateHrefs();
</script>

templates/docs.html
{% extends 'base.html' %}
{% block content %}

<h2>View Document</h2>

{% include 'trix.html' %}

<script>
    data = {{ data | tojson | safe }};
    inputDocumentTitle.value = '{{ data.title }}';
    inputDocumentContent.value = '{{ data.content | safe }}';
    inputDocumentTitle.readOnly = true;
    document.querySelector('trix-editor').editor.element.setAttribute('contentEditable', false)
</script>

<script src="{{ url_for('static',filename='docs.js') }}"></script>

{% endblock %}

templates/get_item.html
{% extends 'base.html' %}
{% block content %}

{% include 'trix.html' %}

<script>
    item = {{ data.item | tojson | safe }};
    itemTitle.innerText = item.title || item.id;
    inputItemTitle.value = item.title || '';
    inputItemContent.value = item.content;
    inputItemTitle.readOnly = true;
    inputItemContent.editor.element.setAttribute('contentEditable', false)
    formItem.setAttribute('data-item-id', item.id)
</script>

<script src="{{ url_for('static',filename='scripts/get_item.js') }}"></script>

{% include 'graph.html' %}

{% endblock %}

templates/graph.html
<div>
    <h2 id="visualization" class="pt-4"><i class="bi bi-share"></i> Visualization <a class="anchor-link" href="#visualization" aria-label="Link to this section: Visualization">#</a></h2>
    <div id="alert-graph-data-missing" class="alert alert-warning d-none" role="alert">
        No graph data available.
    </div>
    <div id="viz-container" class="card my-3 vh-75">
        <div class="card-body">
            <svg id="viz"></svg>
        </div>
    </div>
</div>

<script>
    const searchResponse = {{ data | tojson | safe }};
    const vizContainer = document.querySelector('#viz-container');

    if ((searchResponse?.graph?.nodes ?? []).length > 0) {
        const nodes = searchResponse.graph.nodes;
        let edges = searchResponse.graph.edges;
        links = edges.map(link => ({
            source: link.src,
            target: link.dst,
            index: link.index
        }));
        
        const viz = d3.select('#viz')

        let width = viz.node().getBoundingClientRect().width;
        let height = viz.node().getBoundingClientRect().height;

        const simulation = d3.forceSimulation(nodes)
            .force('link', d3.forceLink(links)
                .id(d => d.id)
                .distance(100))
            .force('charge', d3.forceManyBody().strength(-200))
            .force('center', d3.forceCenter(width / 2, height / 2));

        const colorScale = d3.scaleOrdinal(d3.schemeCategory10);
        
        updateDimensions();

        const link = viz.append('g')
            .selectAll('line')
            .data(links)
            .enter().append('line')
            .style('stroke', '#aaa');

        const node = viz.append('g')
            .attr('class', 'nodes')
            .selectAll('g')
            .data(nodes)
            .enter().append('g')

        node.each(function(d) {
            const nodeElement = d3.select(this);
            const link = nodeElement.append('a')
                .attr('xlink:href', d => `/items/${d.id}`);
            appendNodeContent(link);
        });

        const drag_handler = d3.drag()
            .on('start', dragstarted)
            .on('drag', dragged)
            .on('end', dragended);
        
        drag_handler(node);

        function appendNodeContent(container) {
            container.append('circle')
                .attr('r', 20)
                .attr('fill', d => colorScale(d.labels[0]));

            container.append('text')
                .text(d => d.title || d.labels[0])
                .attr('x', 25)
                .attr('y', 6)
                .style('font-size', '18px')
                .style('font-family', 'Arial, sans-serif');
            
            container.append('foreignObject')
                .attr('width', 40)
                .attr('height', 40)
                .attr('x', -12)
                .attr('y', -19)
                .html(d => `<i class="bi ${d.labels.includes('User') ? 'bi-person' : 'bi-file-text'}" style="font-size:24px;color:white"></i>`);


            container.append('title')
                .text(d => d.title || d.labels[0]);
        }

        function updateDimensions() {
            width = viz.node().getBoundingClientRect().width;
            height = viz.node().getBoundingClientRect().height;
            simulation.force('center', d3.forceCenter(width / 2, height / 2));
            simulation.alpha(0.3).restart();
        }

        node.append('title')
            .text(d => d.title || d.labels[0]);

        simulation.nodes(nodes).on('tick', ticked);
        simulation.force('link').links(links);
        
        window.addEventListener('resize', updateDimensions);

        function ticked() {
            link
                .attr('x1', d => d.source.x)
                .attr('y1', d => d.source.y)
                .attr('x2', d => d.target.x)
                .attr('y2', d => d.target.y);

            node
                .attr('transform', d => {
                    d.x = Math.max(20, Math.min(width - 40, d.x));
                    d.y = Math.max(20, Math.min(height - 40, d.y));
                    return `translate(${d.x}, ${d.y})`;
                });
        }

        function dragstarted(event, d) {
            if (!event.active) simulation.alphaTarget(0.3).restart();
            d.fx = d.x;
            d.fy = d.y;
        }

        function dragged(event, d) {
            d.fx = event.x;
            d.fy = event.y;
        }

        function dragended(event, d) {
            if (!event.active) simulation.alphaTarget(0);
            d.fx = null;
            d.fy = null;
        }
    } else {
        setElementVisibility({
            '#alert-graph-data-missing': true
        });
    }
</script>

templates/index.html
{% extends 'base.html' %}
{% block content %}

{% include 'searchbar.html' %}

{% include 'graph.html' %}

{% endblock %}

templates/label_badges.html
<span class="label-badges">
    {% for label in labels %}
        <a href='{{ url_for("main.search") }}?filter={"labels":["{{ label }}"]}'><span class="badge rounded-pill text-bg-primary">{{ label }}</span></a>
    {% endfor %}
</span>

templates/new.html
{% extends 'base.html' %}
{% block content %}

<h2>Create Document</h2>

{% include 'trix.html' %}

<script src="{{ url_for('static',filename='new.js') }}"></script>

{% endblock %}